// ============================================================================
// CONFIGURATION & COLOR THEMES
// ============================================================================

export const config = {
  form: 'icosahedron',
  density: 3,
  sensitivity: 1.2,
  volume: 0.8,
  visualMode: 'standard',
  colorTheme: 'void',
  colorPrimary: '#ffffff',
  colorSecondary: '#4488ff',
  colorBg: '#020204',
  colorReactivity: 0.55,
  colorCycle: true,
  hueRotateSpeed: 0,
  barLockColors: true,
  cameraMode: 'orbit',
  cameraDistance: 35,
  cameraSpeed: 0.6,
  cameraShake: 0.45,
  cameraFov: 60,
  cameraBeatZoom: true,
  cameraAutoAngles: false,
  particleMode: 'vertex',
  fieldMode: 'harmonic',
  symmetry: 6,
  turbulence: 0.25,
  cohesion: 0.55,
  particleCount: 1500,
  bloomStrength: 0.8,
  bloomRadius: 0.7,
  trailMode: 'medium',
  glitchAmount: 0,
  vignette: 0.35,
  grain: 0.12,
  aberration: 0.08,
  anamorphic: 0,
  scanlines: 0,
  filmLook: 'none',
  environment: 'void',
  fogDensity: 0.008,
  ringCount: 3,
  showInner: true,
  showOuter: true,
  showWaveform: true,
  showBars: false,
  showConnections: true,
  showParticles: true,
  showDeepParticles: true,
  showShockwaves: true,
  showWireframeCore: true,
  showRimGlow: true,
  showRings: true,
  particleSizeMult: 1.0,
  particleBrightness: 1.0,
  shockwaveIntensity: 0.7,
  shockwaveImpactThreshold: 0.55,
  shockwaveCooldown: 0.22,
  showLightRays: false,
  showAurora: false,
  showEnergyField: false,
  showOrbitals: false,
  showSpectrum: true,
  autoPilot: false,
  beatFlash: true,
  synesthesia: false,
  harmonicSnap: true,
  negativeSpace: false,
  reactiveBg: true,
  bgPattern: 'none',
  bgPatternStrength: 0.35,
  smoothness: 0.7,
  modelSpinEnabled: true,
  modelSpinSpeed: 1.0,
  modelSpinAxis: 'xyz',
  modelSpinReactive: true,
  modelSpinReactivity: 1.0,
  modelPulseEnabled: true,
  modelPulseAmount: 1.0
};

export const colorThemes = {
  void: { primary: '#ffffff', secondary: '#888888', bg: '#020204' },
  ember: { primary: '#ff6b35', secondary: '#ff2200', bg: '#0a0505' },
  arctic: { primary: '#88ffff', secondary: '#0066ff', bg: '#020508' },
  neon: { primary: '#ff00ff', secondary: '#00ffff', bg: '#050008' },
  sunset: { primary: '#ff8855', secondary: '#ff3366', bg: '#0a0508' },
  forest: { primary: '#88ff88', secondary: '#00aa44', bg: '#030805' },
  vapor: { primary: '#ff71ce', secondary: '#01cdfe', bg: '#05020a' },
  gold: { primary: '#ffd700', secondary: '#ff8c00', bg: '#080604' },
  blood: { primary: '#ff0044', secondary: '#880022', bg: '#0a0204' },
  ocean: { primary: '#0088ff', secondary: '#004488', bg: '#020408' },
  aurora: { primary: '#00ff88', secondary: '#ff00ff', bg: '#020804' },
  holographic: { primary: '#ff88ff', secondary: '#88ffff', bg: '#040408' },
  plasma: { primary: '#ff4488', secondary: '#4488ff', bg: '#080408' },
  infrared: { primary: '#ff2222', secondary: '#880044', bg: '#0a0204' },
  bioluminescent: { primary: '#00ffaa', secondary: '#0088ff', bg: '#020806' }
};
